version: "3.7"

services:
  kong-database:
    image: postgres:${POSTGRES_VERSION:-latest}
    container_name: kong-database
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-kong}
      - POSTGRES_DB=${POSTGRES_DB:-kong}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-kong}
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    networks:
      - kong_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 5
  kong:
    depends_on:
      - kong-database
    image: kong/kong-gateway:${KONG_VERSION:-latest}
    container_name: kong
    restart: always
    environment:
      - TZ=${TZ:-Asia/Kolkata}
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=${KONG_PG_HOST:-kong-database}
      - KONG_PG_DATABASE=${POSTGRES_DB:-kong}
      - KONG_PG_USER=${POSTGRES_USER:-kong}
      - KONG_PG_PASSWORD=${POSTGRES_PASSWORD:-kong}
      - KONG_ADMIN_GUI_LISTEN=0.0.0.0:8002, 0.0.0.0:8445 ssl
      - KONG_PORTAL=on
      - KONG_VITALS=on
      - KONG_PORTAL_GUI_URL=http://localhost:8003
      - KONG_ADMIN_GUI_URL=http://localhost:8002
      - KONG_ADMIN_LISTEN=${KONG_ADMIN_LISTEN:-127.0.0.1:8001}
      - KONG_PROXY_LISTEN=${KONG_PROXY_LISTEN:-0.0.0.0:8000, 0.0.0.0:8443 ssl http2}
      - KONG_NGINX_HTTP_RESOLVER=${KONG_NGINX_HTTP_RESOLVER:-8.8.8.8}
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_TRUSTED_IPS=0.0.0.0/0,::/0
      - KONG_REAL_IP_RECURSIVE=on
      - KONG_LICENSE_DATA=${KONG_LICENSE_DATA}
      - KONG_LOG_LEVEL=info
      - KONG_WORKER_STATE_UPDATE_FREQUENCY=1
      - KONG_LUA_PACKAGE_PATH=/opt/conf/?.lua;
      - KONG_PLUGINS=bundled,myplugin
      - AUTHENTICATION_URL=http://auth-service:3000
    volumes:
      - ./kong-plugin:/opt/conf/

    networks:
      - kong_network

    working_dir: /opt/conf
    command: sh -c "luarocks make --local && kong start -vv"
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
      - 8003:8003
      - 8004:8004
      - 8443:8443
      - 8444:8444
      - 8445:8445
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 1s
      timeout: 4s
      retries: 5

volumes:
  pg_data:

networks:
  kong_network:
    driver: bridge
